---
# tasks file for nvm- name: check nvm
- name: check nvm
  stat: path={{ nvm.nvm_dir }}/nvm.sh
  register: nvm_sh

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
  environment:
    NVM_DIR: "{{ nvm.nvm_dir }}"
  when: not nvm_sh.stat.exists

- name: copy global profile for nvm
  template: src=nvm.sh.j2 dest=/etc/profile.d/nvm.sh
  become: yes
  when: not nvm_sh.stat.exists

- name: check node
  shell: /bin/bash -lc "NVM_DIR={{ nvm.nvm_dir }} nvm ls | grep {{ node.version }}"
  register: node_installed
  failed_when: node_installed.rc not in [0, 1]

- name: install node
  shell: /bin/bash -lc "NVM_DIR={{ nvm.nvm_dir }} nvm install {{ node.version }}"
  when: node_installed|failed

- name: set default node
  shell: /bin/bash -lc "NVM_DIR={{ nvm.nvm_dir }} nvm alias default {{ node.version }}"
  when: node_installed|failed

  - name: Register nvm to .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      source {{ nvm.nvm_dir }}/nvm.sh
    marker: ""
  when: rbenv_exists is failed

- name: Reload .bash_profile
  shell: source ~/.bashrc
  when: rbenv_exists is failed