---
# tasks file for rails

#-------------
#check
#-------------
- name: check Rails installed
  shell: rails -v | cut -f 2 -d ' '
  register: rails_installed
  ignore_errors: yes

- name: check Rails app dir
  shell: "{{ item }}"
  with_items:
    - cd {{ home_dir }}
    - ls | grep {{ app_name }}
  register: rails_app_created
  changed_when: False
  ignore_errors: yes

- name: check uniciorn service
  shell: ls /etc/init.d/ | grep unicorn
  become: yes
  changed_when: False
  ignore_errors: yes
  register: unicoern_sv

#-------------
#install
#-------------
- name: gem install rails -v {{ rails_version }}
  shell: gem install rails -v {{ rails_version }}
  when: rails_installed.stdout != rails_version

- name: create new rails app
  shell: "{{ item }}"
  with_items:
    - cd {{ home_dir }}
    - rails new {{ app_name }}
  when: rails_app_created is failed

- name: Gemfile modify
  blockinfile:
    path: "{{ home_dir }}/{{ app_name }}/Gemfile"
    block: |
      gem 'unicorn'
    marker: ""
  when: rails_app_created is failed

- name: install unicorn
  shell: "{{ item }}"
  with_items:
    - cd {{ home_dir }}/{{ app_name }}
    - bundle install --path vendor/bundle
  when: rails_app_created is failed

- name: replace nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  when: rails_app_created is failed or unicoern_sv is failed
  become: yes

- name: replace unicorn.rb
  template:
    src: unicorn.rb.j2
    dest: "{{ home_dir }}/{{ app_name }}/config/unicorn.rb"
  when: rails_app_created is failed or unicoern_sv is failed

- name: create unicorn service
  template:
    src: init.d.unicorn.j2
    dest: /etc/init.d/unicorn
    mode: 0755
  when: rails_app_created is failed or unicoern_sv is failed
  become: yes

- name: unicorn service start
  shell: "{{ item }}"
  with_items:
    - systemctl enable unicorn
    - systemctl restart unicorn
  become: yes
  when: rails_app_created is failed or unicoern_sv is failed

- name: nginx service restart
  shell: systemctl restart nginx
  become: yes
  when: rails_app_created is failed or unicoern_sv is failed
