---
# tasks file for rails

#-------------
#check
#-------------
- name: check Rails installed
  shell: rails -v | cut -f 2 -d ' '
  register: rails_installed
  ignore_errors: yes
  tags:
    - rails
    - rails:check

- name: check Rails app dir
  shell: "{{ item }}"
  with_items:
    - cd "{{ home_dir }}"
    - ls | grep "{{ app_name }}"
  register: rails_app_created
  changed_when: False
  ignore_errors: yes
  tags:
    - rails
    - rails:check

- name: check uniciorn service
  shell: ls /etc/init.d/ | grep unicorn
  become: yes
  changed_when: False
  ignore_errors: yes
  register: unicoern_sv
  tags:
    - gem
    - gem:check

#-------------
#install
#-------------
- name: gem install rails -v "{{ rails_version }}"
  shell: gem install rails -v "{{ rails_version }}"
  when: rails_installed.stdout != rails_version
  tags:
    - rails
    - rails:install

- name: create new rails app
  shell: "{{ item }}"
  with_items:
    - cd "{{ home_dir }}"
    - rails new "{{ app_name }}"
  when: rails_app_created is failed
  tags:
    - rails
    - rails:install

- name: install unicorn
  shell: "{{ item }}"
  with_items:
    - cd  "{{ app_name }}"
    - echo 'gem 'unicorn'' >>Gemfile
    - bundle install --path vendor/bundle
  when: rails_app_created is failed
  tags:
    - gem
    - gem:install

- name: replace nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  when: rails_app_created is failed or unicoern_sv is failed
  become: yes
  tags:
    - nginx
    - nginx:config

- name: replace unicorn.rb
  template:
    src: unicorn.rb.j2
    dest: "{{ home_dir }}/{{ app_name }}/config/unicorn.rb"
  when: rails_app_created is failed or unicoern_sv is failed
  tags:
    - gem
    - gem:config

- name: create unicorn service
  template:
    src: init.d.unicorn.j2
    dest: /etc/init.d/unicorn
    mode: 0755
  when: rails_app_created is failed or unicoern_sv is failed
  become: yes
  tags:
    - service
    - service:config

- name: unicorn service start
  shell: "{{ item }}"
  with_items:
    - "systemctl enable unicorn"
    - "systemctl restart unicorn"
  become: yes
  when: rails_app_created is failed or unicoern_sv is failed
  tags:
    - service
    - service:config

- name: nginx service restart
  shell: "systemctl restart nginx"
  become: yes
  when: rails_app_created is failed or unicoern_sv is failed
    - service
    - service:config